"""Seed 4 realistic, fully-finalized example work orders into the
`work_orders` table, one per fictitious injected anomaly pattern described
in `sample-data/README.md` (a slow discharge-pressure drift, a temperature
differential spike, a stuck vibration sensor, and a benign tank-pressure
bump), spanning different equipment, severities, and final statuses.

These are hand-authored (not generated by a live LLM call, to keep this
repo's setup free to run), but they are exactly the kind of output a real
run of `investigate_node` / `draft_work_order_node` against the
corresponding reading in `sample-data/sensor_readings.csv` would plausibly
produce, each carrying a realistic engineer decision.

Run with:
    python -m scripts.seed_examples

Requires `scripts/seed_tags.py` and `scripts/seed_readings.py` to have
already run (the tags and readings this script references must already
exist).
"""
from __future__ import annotations

from datetime import datetime, timedelta, timezone

from app.db.models import SensorTag, WorkOrder
from app.db.session import SessionLocal


def _iso(dt: datetime) -> str:
    return dt.isoformat()


def _trace(base: datetime, node: str, minutes: float, summary: str) -> dict:
    return {"node": node, "timestamp": _iso(base + timedelta(minutes=minutes)), "summary": summary}


def _seed_one(
    *,
    work_order_id: str,
    tag_id: str,
    equipment_id: str,
    equipment_name: str,
    reading_timestamp: datetime,
    reading_value: float,
    anomaly_classification: str,
    anomaly_details: dict,
    retrieved_context: list,
    root_cause_hypothesis: str,
    recommended_response: str,
    citations: list,
    draft_work_order: dict,
    human_decision: str,
    human_feedback: str,
    review_delay_minutes: float,
) -> None:
    with SessionLocal() as db:
        if db.get(WorkOrder, work_order_id) is not None:
            print(f"[skip] work order {work_order_id!r} already seeded")
            return

    t0 = reading_timestamp + timedelta(minutes=1)  # processing began shortly after the reading landed

    if human_decision == "escalate":
        final_status, status = "escalated", "escalated"
    elif human_decision == "dismiss_benign":
        final_status, status = "dismissed_benign", "dismissed_benign"
    else:
        final_status, status = "work_order_approved", "work_order_approved"

    finalize_time = t0 + timedelta(minutes=review_delay_minutes + 0.2)
    reasons_text = "; ".join(anomaly_details.get("reasons", []))
    trace = [
        _trace(t0, "ingest_reading", 0.0, f"Loaded {equipment_name} ({tag_id}) reading at {_iso(reading_timestamp)}."),
        _trace(t0, "detect_anomaly", 0.1, f"Classified as {anomaly_classification.upper()}: {reasons_text}"),
        _trace(
            t0,
            "investigate",
            0.6,
            f"Investigated via {len(retrieved_context)} retrieved manual/incident excerpt(s); drafted root-cause hypothesis.",
        ),
        _trace(t0, "draft_work_order", 1.0, "Drafted work order with LLM-written title/description/priority."),
        _trace(t0, "engineer_review", review_delay_minutes, f"Engineer decision={human_decision} | {human_feedback[:200]}"),
        _trace(t0, "finalize", review_delay_minutes + 0.2, f"Work order finalized with status={final_status}."),
    ]

    state_snapshot = {
        "anomaly_classification": anomaly_classification,
        "anomaly_details": anomaly_details,
        "retrieved_context": retrieved_context,
        "root_cause_hypothesis": root_cause_hypothesis,
        "recommended_response": recommended_response,
        "citations": citations,
        "draft_work_order": draft_work_order,
        "human_decision": human_decision,
        "human_feedback": human_feedback,
        "final_status": final_status,
        "status": status,
    }

    work_order = WorkOrder(
        id=work_order_id,
        tag_id=tag_id,
        equipment_id=equipment_id,
        equipment_name=equipment_name,
        reading_timestamp=reading_timestamp,
        reading_value=reading_value,
        status=status,
        final_status=final_status,
        anomaly_classification=anomaly_classification,
        anomaly_details=anomaly_details,
        retrieved_context=retrieved_context,
        root_cause_hypothesis=root_cause_hypothesis,
        recommended_response=recommended_response,
        citations=citations,
        draft_work_order=draft_work_order,
        human_decision=human_decision,
        human_feedback=human_feedback,
        trace=trace,
        state_snapshot=state_snapshot,
        error=None,
        created_at=t0,
        updated_at=finalize_time,
    )
    with SessionLocal() as db:
        db.add(work_order)
        db.commit()

        tag = db.get(SensorTag, tag_id)
        if tag is not None:
            tag.current_status = anomaly_classification
            tag.last_evaluated_at = reading_timestamp
            tag.last_work_order_id = work_order_id
            db.commit()

    print(f"[seeded] work order {work_order_id!r} ({tag_id}, status={status})")


def seed() -> None:
    # ---------------------------------------------------------------
    # C-201 discharge pressure -- slow drift into the critical range.
    # Escalated by the engineer given the safety-relevant pressure system.
    # ---------------------------------------------------------------
    _seed_one(
        work_order_id="seed-c201-discharge-pressure-drift",
        tag_id="C-201-DISCH-PRESS",
        equipment_id="C-201",
        equipment_name="Process Gas Compressor C-201",
        reading_timestamp=datetime(2026, 9, 15, 19, 0, 0, tzinfo=timezone.utc),
        reading_value=975.59,
        anomaly_classification="critical",
        anomaly_details={
            "rolling_mean": 928.6,
            "rolling_std": 23.23,
            "z_score": 2.02,
            "rate_per_hour": 0.78,
            "stuck_detected": False,
            "threshold_breach": "critical_high",
            "history_window_size": 168,
            "reasons": ["value 975.59 breaches critical threshold (critical_high)"],
        },
        retrieved_context=[
            {
                "chunk_id": "compressor-c-201-discharge-pressure-high-possible-causes-and-response-procedure-manual-1",
                "doc_type": "manual",
                "title": "Compressor C-201 Discharge Pressure High: Possible Causes and Response Procedure",
                "equipment_id": "C-201",
                "equipment_name": "Process Gas Compressor C-201",
                "text": (
                    "A gradual upward drift in discharge pressure over a period of hours to days, rather than a "
                    "sudden step change, is most commonly associated with progressive fouling or partial blockage "
                    "downstream of the compressor -- typically at the anti-surge control valve, the discharge check "
                    "valve, or the inlet strainers on the downstream cryogenic heat exchanger train."
                ),
                "score": 0.87,
            },
            {
                "chunk_id": "incident-report-process-gas-compressor-c-201-discharge-pressure-drift-april-2025-incident-2",
                "doc_type": "incident",
                "title": "Incident Report - Process Gas Compressor C-201 Discharge Pressure Drift (April 2025)",
                "equipment_id": "C-201",
                "equipment_name": "Process Gas Compressor C-201",
                "text": (
                    "Inspection during the following planned outage found significant fouling buildup at the "
                    "discharge check valve and the inlet strainer basket on the downstream cryogenic heat exchanger "
                    "train, consistent with the progressive fouling downstream of the compressor cause."
                ),
                "score": 0.83,
            },
        ],
        root_cause_hypothesis=(
            "Most likely progressive fouling or partial blockage downstream of compressor C-201 -- likely at the "
            "anti-surge valve, discharge check valve, or the downstream cryogenic heat exchanger inlet strainers "
            "-- consistent with a near-identical drift event in April 2025 that was traced to check valve and "
            "strainer fouling. This is a hypothesis for engineer confirmation, not a certainty."
        ),
        recommended_response=(
            "Cross-check the cryogenic heat exchanger inlet flow trend for a corresponding decrease (a strong "
            "corroborating signal per the April 2025 incident); inspect the anti-surge valve position feedback for "
            "an unexpected closing bias; reduce compressor throughput per the unit operating procedure while a "
            "strainer/check-valve inspection is scheduled, rather than waiting for the high-high trip."
        ),
        citations=[
            "Manual: Compressor C-201 Discharge Pressure High: Possible Causes and Response Procedure",
            "Incident: Incident Report - Process Gas Compressor C-201 Discharge Pressure Drift (April 2025)",
        ],
        draft_work_order={
            "tag_id": "C-201-DISCH-PRESS",
            "tag_name": "Compressor C-201 Discharge Pressure",
            "equipment_id": "C-201",
            "equipment_name": "Process Gas Compressor C-201",
            "observed_anomaly": (
                "Compressor C-201 Discharge Pressure reading of 975.59 psig at 2026-09-15T19:00:00+00:00, "
                "classified CRITICAL: value 975.59 breaches critical threshold (critical_high)."
            ),
            "severity": "critical",
            "title": "Investigate critical discharge pressure drift on C-201",
            "description": (
                "Discharge pressure on compressor C-201 has drifted from a normal baseline near 905 psig to "
                "975.59 psig over the preceding five days, now above the 960 psig critical threshold. This matches "
                "the profile of progressive downstream fouling seen in an April 2025 incident on this same "
                "compressor. Recommend cross-checking downstream exchanger inlet flow, inspecting the anti-surge "
                "valve and discharge check valve, and reducing throughput while an inspection is scheduled. This "
                "is a draft recommendation requiring engineer review and approval and does not authorize any "
                "automatic equipment action."
            ),
            "recommended_action": (
                "Cross-check downstream flow, inspect anti-surge valve and discharge check valve, reduce "
                "throughput pending inspection."
            ),
            "priority": "urgent",
        },
        human_decision="escalate",
        human_feedback=(
            "Agree with the fouling hypothesis given the April 2025 precedent -- escalating to the on-call "
            "reliability engineer for an immediate throughput reduction rather than waiting for next shift."
        ),
        review_delay_minutes=18,
    )

    # ---------------------------------------------------------------
    # E-101 temperature differential -- sudden spike, self-clearing.
    # Approved as a logged/trended event per the manual's recurrence policy.
    # ---------------------------------------------------------------
    _seed_one(
        work_order_id="seed-e101-temperature-spike",
        tag_id="E-101-DELTA-T",
        equipment_id="E-101",
        equipment_name="Cryogenic Heat Exchanger E-101",
        reading_timestamp=datetime(2026, 8, 31, 2, 0, 0, tzinfo=timezone.utc),
        reading_value=10.86,
        anomaly_classification="critical",
        anomaly_details={
            "rolling_mean": 4.27,
            "rolling_std": 0.77,
            "z_score": 8.58,
            "rate_per_hour": 0.09,
            "stuck_detected": False,
            "threshold_breach": "critical_high",
            "history_window_size": 168,
            "reasons": ["value 10.86 breaches critical threshold (critical_high)"],
        },
        retrieved_context=[
            {
                "chunk_id": "cryogenic-heat-exchanger-e-101-temperature-differential-troubleshooting-guide-manual-1",
                "doc_type": "manual",
                "title": "Cryogenic Heat Exchanger E-101 Temperature Differential Troubleshooting Guide",
                "equipment_id": "E-101",
                "equipment_name": "Cryogenic Heat Exchanger E-101",
                "text": (
                    "A sudden spike well above this range, developing over a small number of hours rather than "
                    "gradually, is the signature most often associated with localized fouling or ice/hydrate "
                    "formation on the process-side passages of the exchanger."
                ),
                "score": 0.89,
            },
            {
                "chunk_id": "incident-report-cryogenic-heat-exchanger-e-101-temperature-differential-spike-july-2025-incident-2",
                "doc_type": "incident",
                "title": "Incident Report - Cryogenic Heat Exchanger E-101 Temperature Differential Spike (July 2025)",
                "equipment_id": "E-101",
                "equipment_name": "Cryogenic Heat Exchanger E-101",
                "text": (
                    "The investigating engineer concluded the most likely cause was transient hydrate/ice "
                    "formation on a subset of the exchanger's process-side passages, triggered by a moisture "
                    "excursion, which temporarily reduced effective heat transfer area."
                ),
                "score": 0.85,
            },
        ],
        root_cause_hypothesis=(
            "Likely transient hydrate/ice formation on a subset of E-101's process-side passages, most plausibly "
            "triggered by a brief feed gas moisture excursion, closely matching a July 2025 event on this same "
            "exchanger that self-cleared. A hypothesis for engineer confirmation, not a certainty."
        ),
        recommended_response=(
            "Check upstream feed gas moisture/dew point trends for a coincident excursion; monitor whether the "
            "differential decays back toward baseline within a few hours (consistent with the July 2025 "
            "precedent); if it has not begun decaying within 4-6 hours or exceeds the critical threshold "
            "persistently, reduce throughput and consider a planned deicing cycle. Log this event regardless, "
            "since two or more spikes within 90 days should trigger a fuller inspection."
        ),
        citations=[
            "Manual: Cryogenic Heat Exchanger E-101 Temperature Differential Troubleshooting Guide",
            "Incident: Incident Report - Cryogenic Heat Exchanger E-101 Temperature Differential Spike (July 2025)",
        ],
        draft_work_order={
            "tag_id": "E-101-DELTA-T",
            "tag_name": "Cryogenic Heat Exchanger E-101 Temperature Differential",
            "equipment_id": "E-101",
            "equipment_name": "Cryogenic Heat Exchanger E-101",
            "observed_anomaly": (
                "Cryogenic Heat Exchanger E-101 Temperature Differential reading of 10.86 degC at "
                "2026-08-31T02:00:00+00:00, classified CRITICAL: value 10.86 breaches critical threshold "
                "(critical_high)."
            ),
            "severity": "critical",
            "title": "Investigate temperature differential spike on E-101",
            "description": (
                "E-101's warm-end-minus-cold-end temperature differential spiked from a normal ~4.2 degC baseline "
                "to 10.86 degC. This closely matches a July 2025 event on the same exchanger attributed to "
                "transient hydrate/ice formation from a feed gas moisture excursion, which self-cleared within "
                "about 10 hours. Recommend checking feed gas moisture trends and monitoring for decay toward "
                "baseline before considering a deicing cycle. This is a draft recommendation requiring engineer "
                "review and approval and does not authorize any automatic equipment action."
            ),
            "recommended_action": "Check feed gas moisture trend, monitor for decay toward baseline, log for 90-day recurrence tracking.",
            "priority": "high",
        },
        human_decision="approve",
        human_feedback=(
            "Confirmed a coincident moisture analyzer excursion, consistent with the July 2025 precedent; "
            "differential decayed back to baseline within 9 hours. Approving as logged/trended, no further "
            "action needed unless it recurs."
        ),
        review_delay_minutes=25,
    )

    # ---------------------------------------------------------------
    # P-401 vibration -- sensor flat/stuck at a plausible-looking value.
    # Approved: dispatch a technician to check the transmitter wiring.
    # ---------------------------------------------------------------
    _seed_one(
        work_order_id="seed-p401-vibration-stuck",
        tag_id="P-401-VIB",
        equipment_id="P-401",
        equipment_name="LNG Feed Pump P-401",
        reading_timestamp=datetime(2026, 9, 5, 20, 0, 0, tzinfo=timezone.utc),
        reading_value=2.75,
        anomaly_classification="critical",
        anomaly_details={
            "rolling_mean": 2.61,
            "rolling_std": 0.19,
            "z_score": 0.74,
            "rate_per_hour": 0.01,
            "stuck_detected": True,
            "threshold_breach": "none",
            "history_window_size": 168,
            "reasons": [
                "sensor appears stuck/flat: last 7 readings have std=0.0000, far below the tag's normal std=0.1858"
            ],
        },
        retrieved_context=[
            {
                "chunk_id": "feed-pump-p-401-vibration-monitoring-guide-manual-2",
                "doc_type": "manual",
                "title": "Feed Pump P-401 Vibration Monitoring Guide",
                "equipment_id": "P-401",
                "equipment_name": "LNG Feed Pump P-401",
                "text": (
                    "A reading that instead becomes unusually flat -- showing little or no minute-to-minute "
                    "variation where the tag would normally show continuous small fluctuations -- is a strong "
                    "signature of a stuck, frozen, or failed vibration transmitter or data acquisition path, NOT "
                    "a real mechanical condition."
                ),
                "score": 0.91,
            },
            {
                "chunk_id": "incident-report-lng-feed-pump-p-401-vibration-sensor-fault-november-2025-incident-2",
                "doc_type": "incident",
                "title": "Incident Report - LNG Feed Pump P-401 Vibration Sensor Fault (November 2025)",
                "equipment_id": "P-401",
                "equipment_name": "LNG Feed Pump P-401",
                "text": (
                    "A loose signal wiring connection at the vibration transmitter's junction box was found to be "
                    "the cause; the transmitter had latched onto its last valid reading rather than failing to a "
                    "clearly abnormal value."
                ),
                "score": 0.88,
            },
        ],
        root_cause_hypothesis=(
            "Most likely a stuck or frozen vibration transmitter (a loss of monitoring visibility, not a real "
            "mechanical condition) -- the reading has shown zero variance for an extended period despite the "
            "value itself looking plausible, closely matching a November 2025 incident on this same pump caused "
            "by a loose transmitter wiring connection. A hypothesis for engineer confirmation, not a certainty."
        ),
        recommended_response=(
            "Treat this as an instrumentation fault regardless of the numeric value shown; dispatch a technician "
            "to verify the transmitter and local readout in the field per the November 2025 precedent (loose "
            "junction box wiring); do not rely on this tag for pump health monitoring until confirmed working "
            "again."
        ),
        citations=[
            "Manual: Feed Pump P-401 Vibration Monitoring Guide",
            "Incident: Incident Report - LNG Feed Pump P-401 Vibration Sensor Fault (November 2025)",
        ],
        draft_work_order={
            "tag_id": "P-401-VIB",
            "tag_name": "Feed Pump P-401 Vibration",
            "equipment_id": "P-401",
            "equipment_name": "LNG Feed Pump P-401",
            "observed_anomaly": (
                "Feed Pump P-401 Vibration reading of 2.75 mm/s RMS at 2026-09-05T20:00:00+00:00, classified "
                "CRITICAL: sensor appears stuck/flat (zero variance over the last 7 readings vs. normal std "
                "0.19)."
            ),
            "severity": "critical",
            "title": "Dispatch technician: P-401 vibration transmitter appears stuck",
            "description": (
                "P-401's vibration reading has been flat at 2.75 mm/s RMS with no minute-to-minute variation for "
                "an extended period -- a value that looks normal but represents a complete loss of monitoring "
                "visibility on this pump, matching a November 2025 incident traced to a loose transmitter wiring "
                "connection. Recommend dispatching a technician to verify the transmitter and local readout in "
                "the field. This is a draft recommendation requiring engineer review and approval and does not "
                "authorize any automatic equipment action."
            ),
            "recommended_action": "Dispatch technician to verify vibration transmitter wiring and local readout in the field.",
            "priority": "high",
        },
        human_decision="approve",
        human_feedback=(
            "Agreed -- this looks like the same wiring fault pattern as November 2025. Approving work order to "
            "dispatch I&E technician to check the junction box."
        ),
        review_delay_minutes=40,
    )

    # ---------------------------------------------------------------
    # T-101 tank pressure -- brief, benign venting-related bump.
    # Dismissed as benign after confirming the scheduled vent operation.
    # ---------------------------------------------------------------
    _seed_one(
        work_order_id="seed-t101-pressure-benign-bump",
        tag_id="T-101-PRESS",
        equipment_id="T-101",
        equipment_name="LNG Storage Tank T-101",
        reading_timestamp=datetime(2026, 8, 25, 8, 0, 0, tzinfo=timezone.utc),
        reading_value=26.27,
        anomaly_classification="warning",
        anomaly_details={
            "rolling_mean": 14.14,
            "rolling_std": 1.12,
            "z_score": 10.87,
            "rate_per_hour": 0.02,
            "stuck_detected": False,
            "threshold_breach": "warning_high",
            "history_window_size": 168,
            "reasons": ["value 26.27 breaches normal-range threshold (warning_high)"],
        },
        retrieved_context=[
            {
                "chunk_id": "lng-storage-tank-t-101-vapor-space-pressure-management-manual-1",
                "doc_type": "manual",
                "title": "LNG Storage Tank T-101 Vapor Space Pressure Management",
                "equipment_id": "T-101",
                "equipment_name": "LNG Storage Tank T-101",
                "text": (
                    "Brief excursions above this range, typically lasting one to a few hours, are expected during "
                    "scheduled boil-off gas venting operations, planned tank pressure-relief cycles, or "
                    "immediately following a large LNG receipt that displaces vapor space."
                ),
                "score": 0.9,
            }
        ],
        root_cause_hypothesis=(
            "Most likely a benign, expected pressure bump from a scheduled boil-off gas venting operation, per "
            "the tank pressure management guide -- not indicative of a relief system issue, provided the "
            "pressure returns toward baseline within a few hours. A hypothesis for engineer confirmation."
        ),
        recommended_response=(
            "Check the operations log for a scheduled venting operation or LNG receipt coinciding with this "
            "reading; if confirmed and the pressure trend shows signs of returning toward baseline, this can be "
            "logged and dismissed as benign per the standard guidance."
        ),
        citations=["Manual: LNG Storage Tank T-101 Vapor Space Pressure Management"],
        draft_work_order={
            "tag_id": "T-101-PRESS",
            "tag_name": "LNG Storage Tank T-101 Vapor Space Pressure",
            "equipment_id": "T-101",
            "equipment_name": "LNG Storage Tank T-101",
            "observed_anomaly": (
                "LNG Storage Tank T-101 Vapor Space Pressure reading of 26.27 kPag at 2026-08-25T08:00:00+00:00, "
                "classified WARNING: value 26.27 breaches normal-range threshold (warning_high)."
            ),
            "severity": "warning",
            "title": "Confirm benign pressure bump on T-101 vapor space",
            "description": (
                "T-101 vapor-space pressure briefly rose to 26.27 kPag, above the 22 kPag normal maximum but well "
                "below the 30 kPag critical threshold. This is consistent with an expected, short-duration bump "
                "from a scheduled boil-off gas venting operation. Recommend confirming against the operations log "
                "and monitoring for return to baseline. This is a draft recommendation requiring engineer review "
                "and approval and does not authorize any automatic equipment action."
            ),
            "recommended_action": "Confirm scheduled venting operation in the ops log and monitor for return to baseline.",
            "priority": "low",
        },
        human_decision="dismiss_benign",
        human_feedback=(
            "Confirmed a scheduled boil-off vent was logged at this time and pressure returned to 14 kPag within "
            "two hours. Dismissing as benign; no work order needed."
        ),
        review_delay_minutes=12,
    )

    print(
        "[done] seeded 4 example work orders across C-201 (drift/escalated) / E-101 (spike/approved) / "
        "P-401 (stuck sensor/approved) / T-101 (benign bump/dismissed)"
    )


if __name__ == "__main__":
    seed()
